In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("test/test_data_to_predictnikkei225.csv", header=None)

In [5]:
data

0    1         2       3      4     5     6         7
0   117.90  4.4  526879.7   97.16   81.4  49.1  46.1  16361.54
1   119.04  4.0  531688.3   97.22   81.8  51.0  51.1  17353.67
2   111.69  3.9  520715.8   98.57   84.7  44.3  57.5  14691.41
3    90.69  4.3  489501.1   97.23  101.0  38.7  52.5   9043.12
4    92.97  5.0  500354.0   96.53   95.3  41.5  48.6  10654.79
5    81.18  4.8  491408.5   96.27  100.7  42.8  47.4  10398.10
6    76.93  4.5  494957.2   96.22   97.1  43.9  46.7   8560.11
7    86.72  4.2  503175.5   96.55  100.2  47.0  47.0  10688.11
8   105.28  3.7  513698.0   99.21   98.8  54.0  47.7  15908.88
9   119.67  3.5  530465.7  100.00   98.2  56.3  49.1  17408.71
10  120.30  3.2  537289.4   99.88  100.2  55.9  52.4  18450.98

In [121]:
X = data.iloc[:,0:7]

In [122]:
X

0    1         2       3      4     5     6
0   117.90  4.4  526879.7   97.16   81.4  49.1  46.1
1   119.04  4.0  531688.3   97.22   81.8  51.0  51.1
2   111.69  3.9  520715.8   98.57   84.7  44.3  57.5
3    90.69  4.3  489501.1   97.23  101.0  38.7  52.5
4    92.97  5.0  500354.0   96.53   95.3  41.5  48.6
5    81.18  4.8  491408.5   96.27  100.7  42.8  47.4
6    76.93  4.5  494957.2   96.22   97.1  43.9  46.7
7    86.72  4.2  503175.5   96.55  100.2  47.0  47.0
8   105.28  3.7  513698.0   99.21   98.8  54.0  47.7
9   119.67  3.5  530465.7  100.00   98.2  56.3  49.1
10  120.30  3.2  537289.4   99.88  100.2  55.9  52.4

In [123]:
X = X.values

In [124]:
from sklearn import preprocessing
# normalize data
X = preprocessing.scale(X)

In [125]:
X

array([[ 0.99450445,  0.50775712,  0.84278114, -0.40246424, -1.75192335,
         0.24664409, -1.08246504],
       [ 1.06595971, -0.26263299,  1.12937988, -0.35877569, -1.69839236,
         0.57708393,  0.44408822],
       [ 0.60526135, -0.45523052,  0.47540477,  0.62421674, -1.31029267,
        -0.5881513 ,  2.39807639],
       [-0.71101968,  0.31515959, -1.38503146, -0.35149426,  0.87109522,
        -1.56207925,  0.87152313],
       [-0.56810917,  1.66334228, -0.73818467, -0.86119404,  0.1082786 ,
        -1.07511527, -0.31918841],
       [-1.30710695,  1.27814723, -1.27134797, -1.0505111 ,  0.83094698,
        -0.84902486, -0.68556119],
       [-1.57349716,  0.70035464, -1.05984089, -1.08691823,  0.34916806,
        -0.65771758, -0.89927865],
       [-0.95985948,  0.12256206, -0.57001965, -0.84663119,  0.76403324,
        -0.11857889, -0.80768545],
       [ 0.20348223, -0.84042557,  0.05713488,  1.09022797,  0.57667477,
         1.09883105, -0.59396799],
       [ 1.10544814, -1.2256

In [126]:
Y = data.iloc[:,7]

In [127]:
Y = Y.values

In [128]:
Y

array([ 16361.54,  17353.67,  14691.41,   9043.12,  10654.79,  10398.1 ,
         8560.11,  10688.11,  15908.88,  17408.71,  18450.98])

In [129]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8)

In [130]:
print("X_train:{}".format(X_train.shape))
print("X_test:{}".format(X_test.shape))
print("Y_train:{}".format(Y_train.shape))
print("Y_test:{}".format(Y_test.shape))

X_train:(8, 7)
X_test:(3, 7)
Y_train:(8,)
Y_test:(3,)


In [131]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.layers.advanced_activations import PReLU
from keras.optimizers import SGD

In [132]:
n_in = len(X[0])
n_hidden = 200
n_out = 1

In [133]:
len(X[0])

7

In [134]:
model = Sequential()
model.add(Dense(n_hidden, input_dim=n_in))
model.add(Activation('relu'))

model.add(Dense(n_hidden))
model.add(Activation('relu'))

model.add(Dense(n_out))

model.compile(loss='mean_squared_error',
              optimizer=SGD(lr=0.01),
metrics=['accuracy'])

In [137]:
epochs = 1000
batch_size = 1

In [138]:
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size)

Epoch 1/1000
8/8 [==============================] - 0s - loss: 970935763437214716919808.0000 - acc: 0.0000e+00      
Epoch 2/1000
8/8 [==============================] - 0s - loss: 702761177434079455346688.0000 - acc: 0.0000e+00     
Epoch 3/1000
8/8 [==============================] - 0s - loss: 508656830631545122324480.0000 - acc: 0.0000e+00     
Epoch 4/1000
8/8 [==============================] - 0s - loss: 368164684873117384835072.0000 - acc: 0.0000e+00     
Epoch 5/1000
8/8 [==============================] - 0s - loss: 266476758217014162489344.0000 - acc: 0.0000e+00     
Epoch 6/1000
8/8 [==============================] - 0s - loss: 192875282939027533070336.0000 - acc: 0.0000e+00     
Epoch 7/1000
8/8 [==============================] - 0s - loss: 139602703972320480854016.0000 - acc: 0.0000e+00     
Epoch 8/1000
8/8 [==============================] - 0s - loss: 101044114571372473090048.0000 - acc: 0.0000e+00     
Epoch 9/1000
8/8 [==============================] - 0s - loss: 73135504

In [139]:
loss_and_metrics = model.evaluate(X_test, Y_test)
print(loss_and_metrics)

3/3 [==============================] - 0s
[9569607.0, 0.0]


In [140]:
print("コスト関数の値:{}".format(loss_and_metrics[0]))

コスト関数の値:9569607.0


In [141]:
y_pred = model.predict(X_test)

In [142]:
y_pred

array([[ 14087.14355469],
       [ 14087.14355469],
       [ 14087.14355469]], dtype=float32)

In [143]:
X_test

array([[-1.30710695,  1.27814723, -1.27134797, -1.0505111 ,  0.83094698,
        -0.84902486, -0.68556119],
       [ 0.20348223, -0.84042557,  0.05713488,  1.09022797,  0.57667477,
         1.09883105, -0.59396799],
       [-0.56810917,  1.66334228, -0.73818467, -0.86119404,  0.1082786 ,
        -1.07511527, -0.31918841]])

In [207]:
y_pred = model.predict(X_test[1].reshape((1, 7)))

In [208]:
y_pred

array([[ 14087.14355469]], dtype=float32)

In [144]:
#為替　80　円/ドル
#失業率　5%
#GDP　400兆
#物価　90
#財政出動　50兆
#税収　30兆
#不動産価格　40　は不況だから、日経平均はどうなるか　実験

In [178]:
test_resource = np.array([80,5,400,90,50,30,40])

In [179]:
test_resource.shape

(7,)

In [195]:
test_resource = test_resource.reshape((1, 7))

In [196]:
test_resource

array([[ 80,   5, 400,  90,  50,  30,  40]])

In [198]:
pred = model.predict(test_resource)

In [199]:
pred

array([[ 14087.14355469]], dtype=float32)

In [200]:
#為替　120　円/ドル
#失業率　2%
#GDP　600兆
#物価　90
#財政出動　50兆
#税収　30兆
#不動産価格　40　は景気を上向きにしたら日経平均はどうなるか　実験

In [201]:
test_resource2 = np.array([120,5,400,90,50,30,40])

In [202]:
test_resource2 = test_resource2.reshape((1, 7))

In [203]:
test_resource2

array([[120,   5, 400,  90,  50,  30,  40]])

In [204]:
pred = model.predict(test_resource2)

In [205]:
pred

array([[ 14087.14355469]], dtype=float32)