In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

In [2]:
data = pd.read_csv("test/simpletest.csv", header=None)

In [3]:
data

0    1    2    3    4    5    6    7
0    90   89   80   70   90   95   70  500
1    50   65   70   75   88   90   80  450
2   100  100  100  100  100  100  100  700
3    90   90   90   90   90   90   90  650
4    80   80   80   80   80   80   80  600
5    70   70   70   70   70   70   70  550
6    60   60   60   60   60   60   60  500
7    50   50   50   50   50   50   50  450
8    40   40   40   40   40   40   40  400
9    30   30   30   30   30   30   30  350
10   20   20   20   20   20   20   20  300
11   10   10   10   10   10   10   10  250
12    0    0    0    0    0    0    0  200
13   70   75   80   90   70   55   55  500
14   88   78   68   58   78   80   90  480
15   90   40   30   20   10   10   10  300
16    5    5    5    5    5    5    5  230
17   30   30   34   70   70   85   90  400
18   50   80   90   80   90  100   50  500
19   80   80   80   80   65   75   89  550
20  100   90   30   70   80   80   40  500

In [5]:
X = data.iloc[:,0:7]
X = X.values
X

array([[ 90,  89,  80,  70,  90,  95,  70],
       [ 50,  65,  70,  75,  88,  90,  80],
       [100, 100, 100, 100, 100, 100, 100],
       [ 90,  90,  90,  90,  90,  90,  90],
       [ 80,  80,  80,  80,  80,  80,  80],
       [ 70,  70,  70,  70,  70,  70,  70],
       [ 60,  60,  60,  60,  60,  60,  60],
       [ 50,  50,  50,  50,  50,  50,  50],
       [ 40,  40,  40,  40,  40,  40,  40],
       [ 30,  30,  30,  30,  30,  30,  30],
       [ 20,  20,  20,  20,  20,  20,  20],
       [ 10,  10,  10,  10,  10,  10,  10],
       [  0,   0,   0,   0,   0,   0,   0],
       [ 70,  75,  80,  90,  70,  55,  55],
       [ 88,  78,  68,  58,  78,  80,  90],
       [ 90,  40,  30,  20,  10,  10,  10],
       [  5,   5,   5,   5,   5,   5,   5],
       [ 30,  30,  34,  70,  70,  85,  90],
       [ 50,  80,  90,  80,  90, 100,  50],
       [ 80,  80,  80,  80,  65,  75,  89],
       [100,  90,  30,  70,  80,  80,  40]])

In [6]:
Y = data.iloc[:,7]
Y = Y.values
Y

array([500, 450, 700, 650, 600, 550, 500, 450, 400, 350, 300, 250, 200,
       500, 480, 300, 230, 400, 500, 550, 500])

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8)

In [8]:
print("X_train:{}".format(X_train.shape))
print("X_test:{}".format(X_test.shape))
print("Y_train:{}".format(Y_train.shape))
print("Y_test:{}".format(Y_test.shape))

X_train:(16, 7)
X_test:(5, 7)
Y_train:(16,)
Y_test:(5,)


In [18]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.advanced_activations import PReLU
from keras.optimizers import SGD

In [19]:
n_in = len(X[0])
n_hidden = 200
n_out = 1

In [23]:
model = Sequential()
model.add(Dense(n_hidden, input_dim=n_in))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(n_hidden))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(n_out))

model.compile(optimizer='rmsprop',
              loss='mse')

In [24]:
epochs = 100
batch_size = 1

In [25]:
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size)

Epoch 1/100
16/16 [==============================] - 0s - loss: 168637.5945    
Epoch 2/100
16/16 [==============================] - 0s - loss: 104160.6616    
Epoch 3/100
16/16 [==============================] - 0s - loss: 33503.3411     
Epoch 4/100
16/16 [==============================] - 0s - loss: 27229.9094     
Epoch 5/100
16/16 [==============================] - 0s - loss: 19452.6178     
Epoch 6/100
16/16 [==============================] - 0s - loss: 21420.1192    
Epoch 7/100
16/16 [==============================] - 0s - loss: 18976.2674   
Epoch 8/100
16/16 [==============================] - 0s - loss: 29083.2632     
Epoch 9/100
16/16 [==============================] - 0s - loss: 17553.4032   
Epoch 10/100
16/16 [==============================] - 0s - loss: 19792.3307    
Epoch 11/100
16/16 [==============================] - 0s - loss: 16239.5168     
Epoch 12/100
16/16 [==============================] - 0s - loss: 19170.4650     
Epoch 13/100
16/16 [=======================

In [28]:
loss_and_metrics = model.evaluate(X_test, Y_test)
print(loss_and_metrics)
print("コスト関数の値:{}".format(loss_and_metrics))

5/5 [==============================] - 0s
11591.2275391
コスト関数の値:11591.2275390625


In [29]:
pred = model.predict(X_test[1].reshape((1, 7)))

In [30]:
pred

array([[ 287.14755249]], dtype=float32)

In [31]:
test_resource = np.array([80,5,40,9,5,3,0])

In [32]:
test_resource.shape

(7,)

In [33]:
test_resource = test_resource.reshape((1, 7))

In [34]:
test_resource.shape

(1, 7)

In [35]:
pred_o = model.predict(test_resource)

In [36]:
pred_o

array([[ 225.02642822]], dtype=float32)