In [43]:
import numpy as np
from sklearn.model_selection import train_test_split

In [44]:
import pandas as pd

In [45]:
data = pd.read_csv("test/test_data_to_predictnikkei225.csv", header=None)
data

0    1         2       3      4     5     6         7
0   117.90  4.4  526879.7   97.16   81.4  49.1  46.1  16361.54
1   119.04  4.0  531688.3   97.22   81.8  51.0  51.1  17353.67
2   111.69  3.9  520715.8   98.57   84.7  44.3  57.5  14691.41
3    90.69  4.3  489501.1   97.23  101.0  38.7  52.5   9043.12
4    92.97  5.0  500354.0   96.53   95.3  41.5  48.6  10654.79
5    81.18  4.8  491408.5   96.27  100.7  42.8  47.4  10398.10
6    76.93  4.5  494957.2   96.22   97.1  43.9  46.7   8560.11
7    86.72  4.2  503175.5   96.55  100.2  47.0  47.0  10688.11
8   105.28  3.7  513698.0   99.21   98.8  54.0  47.7  15908.88
9   119.67  3.5  530465.7  100.00   98.2  56.3  49.1  17408.71
10  120.30  3.2  537289.4   99.88  100.2  55.9  52.4  18450.98

In [46]:
X = data.iloc[:,0:7]

In [47]:
X

0    1         2       3      4     5     6
0   117.90  4.4  526879.7   97.16   81.4  49.1  46.1
1   119.04  4.0  531688.3   97.22   81.8  51.0  51.1
2   111.69  3.9  520715.8   98.57   84.7  44.3  57.5
3    90.69  4.3  489501.1   97.23  101.0  38.7  52.5
4    92.97  5.0  500354.0   96.53   95.3  41.5  48.6
5    81.18  4.8  491408.5   96.27  100.7  42.8  47.4
6    76.93  4.5  494957.2   96.22   97.1  43.9  46.7
7    86.72  4.2  503175.5   96.55  100.2  47.0  47.0
8   105.28  3.7  513698.0   99.21   98.8  54.0  47.7
9   119.67  3.5  530465.7  100.00   98.2  56.3  49.1
10  120.30  3.2  537289.4   99.88  100.2  55.9  52.4

In [48]:
X = X.values
X

array([[  1.17900000e+02,   4.40000000e+00,   5.26879700e+05,
          9.71600000e+01,   8.14000000e+01,   4.91000000e+01,
          4.61000000e+01],
       [  1.19040000e+02,   4.00000000e+00,   5.31688300e+05,
          9.72200000e+01,   8.18000000e+01,   5.10000000e+01,
          5.11000000e+01],
       [  1.11690000e+02,   3.90000000e+00,   5.20715800e+05,
          9.85700000e+01,   8.47000000e+01,   4.43000000e+01,
          5.75000000e+01],
       [  9.06900000e+01,   4.30000000e+00,   4.89501100e+05,
          9.72300000e+01,   1.01000000e+02,   3.87000000e+01,
          5.25000000e+01],
       [  9.29700000e+01,   5.00000000e+00,   5.00354000e+05,
          9.65300000e+01,   9.53000000e+01,   4.15000000e+01,
          4.86000000e+01],
       [  8.11800000e+01,   4.80000000e+00,   4.91408500e+05,
          9.62700000e+01,   1.00700000e+02,   4.28000000e+01,
          4.74000000e+01],
       [  7.69300000e+01,   4.50000000e+00,   4.94957200e+05,
          9.62200000e+01,   9.71

In [49]:
from sklearn import preprocessing
# normalize data
X = preprocessing.scale(X)

In [50]:
X

array([[ 0.99450445,  0.50775712,  0.84278114, -0.40246424, -1.75192335,
         0.24664409, -1.08246504],
       [ 1.06595971, -0.26263299,  1.12937988, -0.35877569, -1.69839236,
         0.57708393,  0.44408822],
       [ 0.60526135, -0.45523052,  0.47540477,  0.62421674, -1.31029267,
        -0.5881513 ,  2.39807639],
       [-0.71101968,  0.31515959, -1.38503146, -0.35149426,  0.87109522,
        -1.56207925,  0.87152313],
       [-0.56810917,  1.66334228, -0.73818467, -0.86119404,  0.1082786 ,
        -1.07511527, -0.31918841],
       [-1.30710695,  1.27814723, -1.27134797, -1.0505111 ,  0.83094698,
        -0.84902486, -0.68556119],
       [-1.57349716,  0.70035464, -1.05984089, -1.08691823,  0.34916806,
        -0.65771758, -0.89927865],
       [-0.95985948,  0.12256206, -0.57001965, -0.84663119,  0.76403324,
        -0.11857889, -0.80768545],
       [ 0.20348223, -0.84042557,  0.05713488,  1.09022797,  0.57667477,
         1.09883105, -0.59396799],
       [ 1.10544814, -1.2256

In [51]:
Y = data.iloc[:,7]
Y = Y.values
Y = preprocessing.scale(Y)
Y

array([ 0.77655362,  1.05480555,  0.3081504 , -1.27596415, -0.82395657,
       -0.89594763, -1.41142872, -0.81461167,  0.64960099,  1.07024202,
        1.36255617])

In [52]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8)

In [53]:
print("X_train:{}".format(X_train.shape))
print("X_test:{}".format(X_test.shape))
print("Y_train:{}".format(Y_train.shape))
print("Y_test:{}".format(Y_test.shape))

X_train:(8, 7)
X_test:(3, 7)
Y_train:(8,)
Y_test:(3,)


In [54]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.advanced_activations import PReLU
from keras.optimizers import SGD

In [55]:
n_in = len(X[0])
n_hidden = 200
n_out = 1

In [56]:
model = Sequential()
model.add(Dense(n_hidden, input_dim=n_in))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(n_hidden))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(n_out))

model.compile(optimizer='rmsprop',
              loss='mse')

In [57]:
epochs = 100
batch_size = 1

In [58]:
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size)

Epoch 1/100
8/8 [==============================] - 0s - loss: 1.4314     
Epoch 2/100
8/8 [==============================] - 0s - loss: 0.6670     
Epoch 3/100
8/8 [==============================] - 0s - loss: 0.4792     
Epoch 4/100
8/8 [==============================] - 0s - loss: 0.2536     
Epoch 5/100
8/8 [==============================] - 0s - loss: 0.2800     
Epoch 6/100
8/8 [==============================] - 0s - loss: 0.1280     
Epoch 7/100
8/8 [==============================] - 0s - loss: 0.1344     
Epoch 8/100
8/8 [==============================] - 0s - loss: 0.1499     
Epoch 9/100
8/8 [==============================] - 0s - loss: 0.1673     
Epoch 10/100
8/8 [==============================] - 0s - loss: 0.0649     
Epoch 11/100
8/8 [==============================] - 0s - loss: 0.1071     
Epoch 12/100
8/8 [==============================] - 0s - loss: 0.0499     
Epoch 13/100
8/8 [==============================] - 0s - loss: 0.2408     
Epoch 14/100
8/8 [================

In [59]:
loss_and_metrics = model.evaluate(X_test, Y_test)
print("コスト関数の値:{}".format(loss_and_metrics))

3/3 [==============================] - 0s
コスト関数の値:0.0791059210896492


In [60]:
y_pred = model.predict(X_test)
y_pred

array([[-1.3597194 ],
       [ 1.16693234],
       [-0.9374665 ]], dtype=float32)

In [61]:
Z = data.iloc[1,0:7]
print(Z)
Z = Z.values
Z

0       119.04
1         4.00
2    531688.30
3        97.22
4        81.80
5        51.00
6        51.10
Name: 1, dtype: float64


array([  1.19040000e+02,   4.00000000e+00,   5.31688300e+05,
         9.72200000e+01,   8.18000000e+01,   5.10000000e+01,
         5.11000000e+01])

In [62]:
pred = model.predict(Z.reshape(1, 7))

In [74]:
pred[0][0]

143806.59

In [75]:
#為替　80　円/ドル
#失業率　5%
#GDP　400兆
#物価　90
#財政出動　50兆
#税収　30兆
#不動産価格　40　は不況だから、日経平均はどうなるか　実験

In [77]:
test_resource = np.array([80,5,400000,90,50,30,40])

In [78]:
test_resource = test_resource.reshape((1, 7))
test_resource

array([[    80,      5, 400000,     90,     50,     30,     40]])

In [79]:
predtest_1 = model.predict(test_resource)

In [80]:
predtest_1

array([[ 108186.2421875]], dtype=float32)

In [81]:
predtest_1[0][0]

108186.24

In [82]:
#↑不況を反映した日経平均予測値になっている！

In [83]:
#次は、景気がもう少しいい感じの場合

In [84]:
#為替　120　円/ドル
#失業率　2%
#GDP　600兆
#物価　90
#財政出動　50兆
#税収　30兆
#不動産価格　40　は景気を上向きにしたら日経平均はどうなるか　実験

In [88]:
test_resource2 = np.array([120,2,600000,90,50,30,40])
test_resource2 = test_resource2.reshape((1, 7))
test_resource2

array([[   120,      2, 600000,     90,     50,     30,     40]])

In [90]:
predtest_2 = model.predict(test_resource2)

In [91]:
predtest_2[0][0]

162271.72

In [92]:
#↑（実態と違うが一応）景気上昇を反映した日経平均予測値になっている！