In [14]:
#『詳解ディープラーニング』より引用のロジスティック回帰コード　keras版（最新版kerasでないので変数名に注意）の解説メモ　自分用
#利用環境
#keras-2.0.5 numpy-1.13.0 scipy-0.19.1 theano-0.9.0

In [2]:
import numpy as np
from keras.layers.core import Activation
from keras.layers.core import Dense
from keras.models import Sequential

Using TensorFlow backend.


In [3]:
from keras.optimizers import SGD

In [4]:
#↑SGDは確率的勾配降下法（stochastic gradient descent）

In [8]:
model = Sequential()

In [9]:
#Sequential()：計算グラフの基盤を構築するメソッド

In [11]:
model.add(Dense(input_dim=2, units=1))

In [12]:
model.add(Activation('sigmoid'))

In [15]:
#Dense(input_dim=2, units=1) ネットワーク層のユニット数（units　）、インプット（input_dim）・アウトプットunitsの数を定義。Dense：密集した　という意味合い
#層からの出力を確率に変換する関数を選ぶのがActivationメソッド、今回はシグモイド関数をチョイス

In [16]:
model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))

In [17]:
#↑つくった計算グラフmodelの最適化計算の定義をしている
#loss='binary_crossentropy'→最小化対象のコスト関数：クロスエントロピー誤差のコスト関数を定義（これだけでやってくれるとは凄い・・・）
#optimizer=SGD(lr=0.1)　→学習率0.1で、SGD：確率的勾配降下法で重みを最適化

In [18]:
#@@@@@@
#テストデータ生成

In [19]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

In [20]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [21]:
Y

array([[0],
       [1],
       [1],
       [1]])

In [22]:
#@@@@@@

In [23]:
model.fit(X, Y, epochs=20, batch_size=1)

Epoch 1/20
4/4 [==============================] - 0s - loss: 0.7685     
Epoch 2/20
4/4 [==============================] - 0s - loss: 0.6262     
Epoch 3/20
4/4 [==============================] - 0s - loss: 0.5566     
Epoch 4/20
4/4 [==============================] - 0s - loss: 0.5153     
Epoch 5/20
4/4 [==============================] - 0s - loss: 0.4880     
Epoch 6/20
4/4 [==============================] - 0s - loss: 0.4655     
Epoch 7/20
4/4 [==============================] - 0s - loss: 0.4478     
Epoch 8/20
4/4 [==============================] - 0s - loss: 0.4306     
Epoch 9/20
4/4 [==============================] - 0s - loss: 0.4158     
Epoch 10/20
4/4 [==============================] - 0s - loss: 0.4010     
Epoch 11/20
4/4 [==============================] - 0s - loss: 0.3859     
Epoch 12/20
4/4 [==============================] - 0s - loss: 0.3718     
Epoch 13/20
4/4 [==============================] - 0s - loss: 0.3581     
Epoch 14/20
4/4 [==============================

In [24]:
#学習開始　 :epochs学習素材1セットの学習ターン数（nb_epochから変数名が変更された）
#batch_sizeはセット数　batch_size＝１は確率的勾配降下法、batch_size＝２・・・　はミニバッチ学習　batch_size＝(全データ)は普通の最急降下法

In [25]:
classes = model.predict_classes(X, batch_size=1)
probability = model.predict_proba(X, batch_size=1)

1/4 [======>.......................] - ETA: 0s

In [26]:
print(classes)

[[0]
 [1]
 [1]
 [1]]


In [27]:
print(probability)

[[ 0.4545511 ]
 [ 0.82641399]
 [ 0.86812413]
 [ 0.97409803]]


In [28]:
#予測OK