In [31]:
#『詳解ディープラーニング』より引用のロジスティック回帰コード　keras版（最新版kerasでないので変数名に注意）の解説メモ　自分用

In [1]:
import numpy as np
from keras.layers.core import Activation
from keras.layers.core import Dense
from keras.models import Sequential

Using TensorFlow backend.


In [2]:
from keras.optimizers import SGD

In [3]:
#↑SGDは確率的勾配降下法（stochastic gradient descent）

In [4]:
model = Sequential()

In [13]:
#Sequential()：計算グラフの基盤を構築するメソッド

In [7]:
model.add(Dense(input_dim=2, output_dim=1))

In [8]:
model.add(Activation('sigmoid'))

In [9]:
#Dense(input_dim=2, output_dim=1) ネットワーク層のユニット数、インプット・アウトプットの数を定義。Dense：密集した　という意味合い
#層からの出力を確率に変換する関数を選ぶのがActivationメソッド、今回はシグモイド関数をチョイス

In [12]:
model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))

In [14]:
#↑つくった計算グラフmodelの最適化計算の定義をしている
#loss='binary_crossentropy'→最小化対象のコスト関数：クロスエントロピー誤差のコスト関数を定義（これだけでやってくれるとは凄い・・・）
#optimizer=SGD(lr=0.1)　→学習率0.1で、SGD：確率的勾配降下法で重みを最適化

In [16]:
#@@@@@@
#テストデータ生成

In [17]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

In [18]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [19]:
Y

array([[0],
       [1],
       [1],
       [1]])

In [20]:
#@@@@@@

In [24]:
model.fit(X, Y, nb_epoch=200, batch_size=1)

Epoch 1/200
4/4 [==============================] - 0s - loss: 1.0845     
Epoch 2/200
4/4 [==============================] - 0s - loss: 0.9420     
Epoch 3/200
4/4 [==============================] - 0s - loss: 0.8342     
Epoch 4/200
4/4 [==============================] - 0s - loss: 0.7525     
Epoch 5/200
4/4 [==============================] - 0s - loss: 0.6924     
Epoch 6/200
4/4 [==============================] - 0s - loss: 0.6458     
Epoch 7/200
4/4 [==============================] - 0s - loss: 0.6089     
Epoch 8/200
4/4 [==============================] - 0s - loss: 0.5803     
Epoch 9/200
4/4 [==============================] - 0s - loss: 0.5575     
Epoch 10/200
4/4 [==============================] - 0s - loss: 0.5391     
Epoch 11/200
4/4 [==============================] - 0s - loss: 0.5236     
Epoch 12/200
4/4 [==============================] - 0s - loss: 0.5100     
Epoch 13/200
4/4 [==============================] - 0s - loss: 0.4984     
Epoch 14/200
4/4 [================

In [26]:
#学習開始　nb_epoch: 学習素材1セットの学習ターン数（epochsに変数名が変更されたぽい）
#batch_sizeはセット数　batch_size＝１は確率的勾配降下法、batch_size＝２・・・　はミニバッチ学習　batch_size＝(全データ)は普通の最急降下法

In [27]:
classes = model.predict_classes(X, batch_size=1)
probability = model.predict_proba(X, batch_size=1)

1/4 [======>.......................] - ETA: 0s

In [28]:
print(classes)

[[0]
 [1]
 [1]
 [1]]


In [29]:
print(probability)

[[ 0.23339556]
 [ 0.90671355]
 [ 0.91465396]
 [ 0.99708575]]


In [30]:
#予測OK