In [68]:
#『詳解ディープラーニング』より引用のロジスティック回帰コードの解説メモ　自分用

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [29]:
#＠＠＠＠＠＠＠＠＠＠＠＠

In [90]:
w = tf.Variable(tf.zeros([2,1]))
b = tf.Variable(tf.zeros([1]))

In [24]:
# tf.Variableはtensorflowの変数宣言

In [4]:
w

In [5]:
b

In [6]:
print(w)

Tensor("Variable/read:0", shape=(2, 1), dtype=float32)


In [7]:
print(b)

Tensor("Variable_1/read:0", shape=(1,), dtype=float32)


In [102]:
#↑なお、tensol flow のオブジェクトはprint()では中身が見れないので、
#sess = tf.Session()
#print(sess.run(みたいもの))
#とする必要がある

In [25]:
#＠＠＠＠＠＠＠＠＠＠＠＠

In [20]:
tf.zeros([2,1]) 

<tf.Tensor 'zeros_6:0' shape=(2, 1) dtype=float32>

In [19]:
#zero行列をつくる

In [26]:
#＠＠＠＠＠＠＠＠＠＠＠＠

In [17]:
x = tf.placeholder(tf.float32, shape=[None, 2])

In [21]:
#tf.placeholderは後で拡張が勝手にされる変数　shape=[None, 2]　のNone部分の次元の数が変わってもxにぶっこんでくれるという意味あいで、
#型、次元数がかっちり決まっている変数（tf.Variable　）とは異なる

In [27]:
#＠＠＠＠＠＠＠＠＠＠＠＠

In [22]:
tf.matmul(x, w)

<tf.Tensor 'MatMul_1:0' shape=(?, 1) dtype=float32>

In [31]:
#tf.matmul(x, w)は、ｘとwの行列の積

In [28]:
#＠＠＠＠＠＠＠＠＠＠＠＠

In [93]:
x = tf.placeholder(tf.float32, shape=[None, 2])
t = tf.placeholder(tf.float32, shape=[None, 1])
y = tf.nn.sigmoid(tf.matmul(x, w) + b )

In [32]:
#xはR^?*2の可変系変数（自分の造語）　インプットするデータが入る
#wは重み　シータ
# tf.nn.sigmoidはシグモイド関数
#tf.matmul(x, w) はｘとwの行列の積

In [33]:
#＠＠＠＠＠＠＠＠＠＠＠＠

In [94]:
cross_entropy = - tf.reduce_sum(t*tf.log(y) + (1-t)*tf.log(1-y))

In [36]:
#↑これはロジスティック回帰のコスト関数（1/mは考慮しないで取り除いてる模様）

In [95]:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

In [40]:
#tf.train.GradientDescentOptimizer(0.1←学習率).minimize(cross_entropy←コスト関数)

In [41]:
train_step

<tf.Operation 'GradientDescent' type=NoOp>

In [42]:
#＠＠＠＠＠＠＠＠＠＠＠＠

In [96]:
prediction = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)

In [51]:
#上の意味を知るために下記でちょっと実験を行う

In [67]:
#↓tf.equal(a,b)は、a==b でTrue　a != b で　Falseを返す
#なお、tensol flow のオブジェクトはprint()では中身が見れないので、
#sess = tf.Session()
#print(sess.run(みたいもの))
#とする必要がある

In [49]:
sess = tf.Session()

In [50]:
print(sess.run(tf.equal(1,1)))

True


In [65]:
#↓tf.greater(a,b)は、a>b でTrue　a =< b で　Falseを返す ちなみに少数じゃないとエラーになります

In [54]:
print(sess.run(tf.greater(1.5, 0.5)))

True


In [55]:
print(sess.run(tf.greater(0.2, 0.5)))

False


In [64]:
print(sess.run(tf.greater(0.5, 0.5)))

False


In [66]:
#tf.to_float(True)→1.0を返す　tf.to_float(False)→0.0を返す

In [57]:
print(sess.run(tf.to_float(tf.greater(1.5, 0.5))))

1.0


In [58]:
print(sess.run(tf.to_float(tf.greater(2.5, 0.5))))

1.0


In [59]:
print(sess.run(tf.to_float(tf.greater(0.1, 0.5))))

0.0


In [60]:
print(sess.run(tf.to_float(True)))

1.0


In [62]:
print(sess.run(tf.to_float(False)))

0.0


In [71]:
#prediction = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)
#tf.greater(y, 0.5) y>0.5ならTrue　y=<0.5ならFalse
#tf.to_float(tf.greater(y, 0.5))　y>0.5なら1.0　y=<0.5なら０．０
#prediction = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)　tf.to_float(tf.greater(y, 0.5))=1.0 or 0.0 t=1.0 or 0.0で= ならTrue　!=ならFalse

In [72]:
#@@@@@@

In [73]:
#テストデータ生成

In [97]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

In [76]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [77]:
Y

array([[0],
       [1],
       [1],
       [1]])

In [82]:
#@@@@@@@@@@@@

In [98]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [81]:
print(sess.run(init))

None


In [83]:
#initは空データだった　データ入れる前にゼロ行列突っ込んどくみたいな前処理って感じかな

In [84]:
#@@@@@@@@@@@@@@@

In [99]:
for epoch in range(200):
    sess.run(train_step, feed_dict={x:X,t:Y})

In [101]:
#学習　最適化された重みはtrain_stepに、　xはテストデータ　Yは正解ラベル

In [103]:
feed_dict

NameError: name 'feed_dict' is not defined

In [104]:
#feed_dict　はsess内部に補完されているらしく　そもそも見れない模様

In [110]:
#↓prediction変数（上で用意したもの）にsession結果（学習結果）とデータ、ラベルを.eval()メソッドでぶち込むと、正解ラベルと合致してるかTrue Falseの一覧が出て来る

In [105]:
classified = prediction.eval(session= sess, feed_dict={x:X,t:Y})

In [106]:
print(classified)

[[ True]
 [ True]
 [ True]
 [ True]]


In [109]:
#↓y変数（上で用意したシグモイド関数）にsession結果（学習結果）とデータ、ラベルを.eval()メソッドでぶち込むと、出力確率の一覧が出て来る

In [107]:
probability = y.eval(session= sess, feed_dict={x:X,t:Y})

In [108]:
print(probability)

[[ 0.22355038]
 [ 0.91425949]
 [ 0.91425949]
 [ 0.99747425]]


In [111]:
#↑1つめは正解が0なので0.5以下の出力になっているのでこのままでOK　ほかの正解はすべて1なので、0.5以上になっているので計算結果とデータは合致している