In [1]:
#MNISTデータセットのセットアップ

In [2]:
from sklearn import datasets

In [4]:
mnist = datasets.fetch_mldata('MNIST original', data_home='.')

In [5]:
n = len(mnist.data)

In [6]:
n

70000

In [7]:
N=10000

In [9]:
import numpy as np
indices = np.random.permutation(range(n))[:N]

In [11]:
#↑range(n)=0~70000 のなかからN=10000個ランダムに数を取得してアレイにする

In [10]:
indices

array([33266,  8180, 18603, ..., 64920, 51679, 51237])

In [15]:
mnist

{'COL_NAMES': ['label', 'data'],
 'DESCR': 'mldata.org dataset: mnist-original',
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'target': array([ 0.,  0.,  0., ...,  9.,  9.,  9.])}

In [17]:
#↑mnistには画素データが入っているdata部分と正解ラベルが書いてあるtarget部分があるということがわかる

In [16]:
mnist.data[:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [18]:
#↑mnistには画素データが入っているdata部分を表示するとこんな感じ

In [19]:
X = mnist.data[indices]
y = mnist.target[indices]

In [20]:
#indicesの変数分、mnistデータを取得

In [21]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [27]:
np.eye(3)[0]

array([ 1.,  0.,  0.])

In [28]:
np.eye(3)[1]

array([ 0.,  1.,  0.])

In [29]:
np.eye(3)[2]

array([ 0.,  0.,  1.])

In [39]:
np.eye(5)[[0,1,2,1,0]]

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.]])

In [40]:
#np.eyeで単位行列　その後に添え字をリスト表記でつけると単位行列の1の場所を特定できる

In [41]:
y.astype(int)

array([5, 1, 2, ..., 4, 8, 8])

In [42]:
#numpy。astype(int)はint型になるわけね→「astypeは、ndarrayの要素のデータ型を別のデータ型にしたndarrayを生成します。」
#引用元　http://spitta8823.hatenablog.com/entry/2016/03/21/224642

In [43]:
Y = np.eye(10)[y.astype(int)]

In [44]:
Y[:3]

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [45]:
#↑正解ラベルをonehot表現にした

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8)

In [55]:
print("X_train:{}".format(X_train.shape))
print("X_test:{}".format(X_test.shape))
print("Y_train:{}".format(Y_train.shape))
print("Y_test:{}".format(Y_test.shape))

X_train:(8000, 784)
X_test:(2000, 784)
Y_train:(8000, 10)
Y_test:(2000, 10)


In [56]:
#↑8割がトレーニングデータ、2割が検証データに分かれてますね